[tools]
uv = "latest"
"pipx:basedpyright" = "latest"
"github:astral-sh/ruff" = "latest"
"github:facebook/pyrefly" = "latest"

[tasks.build]
description = "Build a project"
run = [
    "docker buildx build --platform linux/amd64 --pull --force-rm --tag unraid9 .",
    "docker save -o unraid9.tar.gz unraid9:latest",
]

[tasks.check]
description = "Check the project"
run = [
    "ruff check .",
    "ruff format .",
    "pyrefly check .",
]
